---
- name: 'Gathering facts'
  when: ansible_facts.keys() | length == 0
  setup: {}

- name: 'Loading OS specific variables from {{ ansible_system | lower }}/{{ ansible_architecture }}.yml'
  ansible.builtin.include_vars:
    name: helm_install
    file: '{{ ansible_system | lower }}/{{ ansible_architecture }}.yml'

- name: 'Downloading and extracting helm to management machine'
  delegate_to: localhost
  run_once: true
  ansible.builtin.import_tasks: steps/download.yml

- name: 'Installing helm'
  ansible.builtin.import_tasks: steps/install.yml
